### ISSUE TITLE
More Tooltips

### ISSUE THREAD

**Issue by vinnymac** [vinnymac/PokeNurse#124]
Some ideas I have seen around additional information on the table around evolves, cp, and IVs.

https://github.com/wwayne/react-tooltip
https://react-bootstrap.github.io/components.html#tooltips
http://styleguide.cfapps.io/react_base_tooltips.html

I think we should add additional tooltips for all of this info. They appear to work well, and the IVs look kind of ugly right now with the ADS nearby. Thoughts?

**Comment by iPaulis** [comment]
Agreed. Tooltips are a nice way to show info that otherwise could be visually overwhelming. ADS could go on tooltips when we hover IV%, although as it is right now is also fine for me. In CP the tooltip could show Max CP for that Pokemon. The additional info for candy/evolves would be great in tooltips. Personally, only with a "+12" in the candy column tooltip or a "+1" in the evolve column tooltip would sufice to understand that you need 12 more candy to evolve all the pidgies you have or you have enough candy to evolve 1 more weedle. Anyway, if pokemon/candy exactly match, there shouldnt be any tooltip.
