### ISSUE TITLE
The window went white

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#143]
While I was mass evolving about 65 pokemon, the window went white, like unloaded. When I tried to open devtools it said the following:
![unloaded](https://cloud.githubusercontent.com/assets/11468889/18210751/5d2b3004-713a-11e6-9cad-e77cb6587d49.PNG)

I cannot tell if the program continued evolving the pokemon or not as there was no sign of what was happening at all.

**Comment by vinnymac** [comment]
Looks like the app became unresponsive the same thing that happens when chrome becomes unresponsive. I added the unresponsive event to the electron main thread, so we will get some logs when this occurs. Not sure how it happens, but I moved pogobuf and the request layer to the renderer thread so I doubt we will see this same problem again soon.
