### ISSUE TITLE
Countdown not working during large evolution spree

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#155]
I queued 68 pokemon to evolve and the progress bar was working and the name of the pokemon being evolved was being updated, but the countdown did not work. You can see it in the screenshots. I opened the console to see what was happening and that was the error that appeared. It continued evolving all pokemon normally though.
![evolve bug](https://cloud.githubusercontent.com/assets/11468889/18407364/e42af326-770e-11e6-95b5-33fdecdf5179.PNG)
![evolve bug 2](https://cloud.githubusercontent.com/assets/11468889/18407365/e7390ecc-770e-11e6-86d7-e69e2a16635f.PNG)

**Comment by vinnymac** [comment]
Looks like [this is the line](https://github.com/vinnymac/PokeNurse/blame/master/app/screens/Table/components/Status.js#L66) causing it. Not sure exactly why it was undefined though, maybe this would happen if the interval somehow got called multiple times after we cleared it. Moving the setInterval work to redux is definitely something we want to do. This bug is certainly not critical though, and shouldn't cause any big issues, unless it prevents the status reset.

EDIT:
The code changes in the `transfer-and-evolve` branch completely get rid of the need for the finished callback, and adds quite a lot of nice logic around transfer and evolve, including error handling. So issues like these should be mitigated if we get that tested and merged.

EDIT 2:
I think everything is good to go on `develop`, I tested this quite a bit, and it seems like everything is fixed here. I could use some testing though.
