### ISSUE TITLE
Bluebird bug

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#160]
Sometimes during a batch transfer an error message window appears like this:
![bluebird bug](https://cloud.githubusercontent.com/assets/11468889/18689918/df32f3ca-7f8b-11e6-8886-aa40c24b16c8.PNG)
It does not happen always, but it happens often. It even happens with single transfers, but this time there is no error message window, only info in console, as shown here:
![bluebird bug 2](https://cloud.githubusercontent.com/assets/11468889/18689985/2bdcca3e-7f8c-11e6-929d-116c4cac8e25.PNG)
This error can also happen during evolves such as here:
![evolve bug 3](https://cloud.githubusercontent.com/assets/11468889/18690012/527710be-7f8c-11e6-9517-4603a2bfc485.PNG)
Bug reproduced in v1.5.2 and v1.5.3.

After the error is shown, all pending operations are stopped. Many times, just clicking transfer or evolve buttons makes the program start working again and complete the transfers or evolves left before the error happened, as they are still selected. However, there is always the possibility that the same error is thrown again. 
I've never had any problem transferring before and if there was I didn't notice because all the selected pokemon were trasnfered anyway, so in practice is like there never was a error to begin with. Now we may be aware of the errors that are happening, but if that makes the transfers stop it doesn't seem very practical in my opinion.

**Comment by vinnymac** [comment]
I can easily prevent it from stopping transfer/evolve when an error happens. But that is a feature not a bug. The advantage is knowing what is failing. If we don't stop the transfer/evolve then we end up in bad situations where we lie and pretend everything worked when it may not have.

It is strange that single transfer/evolves wouldn't show the error message.

One thing I can do however is detect `[INTERNAL]` errors based on the error message, and then I could continue and just log it. I think that might be best in this case. After reading the stacktrace further it sounds like an error in building the envelope which looks bad. I think that this might be due to pogobuf's out of date dependencies. I'll think on this some more.

**Comment by iPaulis** [comment]
It works very nicely now in v1.5.4. The errors appear in console but the transfer process is not interrupted, and it is able to complete all the transfers.
