### ISSUE TITLE
Feature Request: Show IV % in the details modal window

### ISSUE THREAD

**Issue by YesThatAllen** [vinnymac/PokeNurse#179]
As I name my pokemon, I use the IV (well, I use the sum of `100 - IV` so that they sort by name better) it would be very handy if the pokemon view would show the IV % which is normally visible in list view, but always covered when in the detail (so that I can't see it when renaming)

![no-move-highlight](https://cloud.githubusercontent.com/assets/2879972/21582857/c074f58a-d02d-11e6-863f-c737e25a620c.png)

**Comment by vinnymac** [comment]
So I just added a commit to `develop` for templated renaming. I am planning on doing [IV], [ATT], [DEF], and [STA] keywords to refer to those attributes. I saw this ticket also has you doing some templating manually. Instead of adding IV % (which we could make a separate ticket for if you still wanted it), I made a custom one called [VI] where it will do `100 - iv`. Would this suffice as a solution to your problem?

Example:
`Bulba-[VI]` becomes `Bulba-33` (if the iv was 67)

**Comment by YesThatAllen** [comment]
I'd certainly make use of the IV going into the mon's name, but my worry with templated renaming is... who's got the best template?

I'm very happy with mine, but don't want to force it on anyone.  For the purposes of my request, I'd be disabling any naming I couldn't control "how I like it" and would be very happy to just see the IV in the detail screen. 

A discussion on naming is probably best for discord, I'll post more there 😄

**Comment by YesThatAllen** [comment]
yes, after hearing more about how templated renaming works, `[VI]` sending the inverse of the IV % would be great.

I'd still love to see the IVs in the window, too 😜

**Comment by YesThatAllen** [comment]
This is awesome!

![screenshot_2366](https://cloud.githubusercontent.com/assets/2879972/21632895/2deb2f2e-d210-11e6-918d-6be0f9eb4ca9.png)

Thank you!
