### ISSUE TITLE
Google OAuth

### ISSUE THREAD

**Issue by basmith7** [vinnymac/PokeNurse#2]
Any chance of using OAuth with google login. I have 2FA setup and I don't want to give you my google account password.

**Comment by ReDetection** [comment]
Want to note that passwords for applications works fine. however, oauth seems to be more convenient

**Comment by duhminick** [comment]
I don't receive your password in any way.  The only time your password is used is to get a token (https://github.com/cyraxx/pogobuf/blob/master/pogobuf/pogobuf.googlelogin.js#L35), and if you click Remember Me, the password is stored locally.

I'll look into implementing OAuth in the future.

**Comment by vinnymac** [comment]
I am guessing the `Remember Me` option is what @basmith7 was referring to since you store the password in `account.json`. If you added OAuth it would prevent the need for the password to be stored in plain text. Definitely shouldn't be a priority though since you aren't requiring the use of `Remember Me`. Thanks for this tool!

**Comment by basmith7** [comment]
I also use 2FA on my google account. I need OAth to login.

**Comment by vinnymac** [comment]
@basmith7 you can try to use an [AppPassword](https://security.google.com/settings/security/apppasswords) for now instead, until OAuth is added. This is how I login with 2FA on.
