### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nevb** [vinnymac/PokeNurse#212]
Hey
I'm a true beginner and have no clue what I'm supposed to put in the new field for hash keys. If I don't put anything in I can't log in. But what am i supposed to generate a hash key from? Please help :)

**Comment by vinnymac** [comment]
Hey, unfortunately not using a hash key likely won't work anymore and has a higher risk of getting a ban since the default APIs are now using 5704. I might have to change the app so that it no longer allows not using a hash key to prevent anything bad happening to users. If you still want to try to use the app you are likely going to need to [buy one of these](https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer) tokens or find a channel where you can get one for free. In the meantime a lot of users are having trouble logging in, and we have some severe issues. Hopefully niantic will back off a bit and allow this app to help users like it used to.

If you have any more questions please use discord for support.
