### ISSUE TITLE
Finer grain IV

### ISSUE THREAD

**Issue by SteinerKD** [vinnymac/PokeNurse#61]
Would it be possible to get the IV value with a decimal point?
Currently it seems that all values are rounded down to the closest full percent so that .0 and .9 look the same despite being almost a full point apart (not even rounded to the closest value, always down).
Just one decimal would be just fine.

Thank you for your time and effort!

**Comment by mackhankins** [comment]
To my knowledge we aren't altering the IV values.  That's handled from the [pogobuff](https://github.com/cyraxx/pogobuf) library.  You might want to make an issue over there or PR.  Checkout around line [223](https://github.com/cyraxx/pogobuf/blob/master/pogobuf/pogobuf.utils.js#L223)

**Comment by SteinerKD** [comment]
Ok, will do. the one decimal seems to be the de facto standard used by all IV tools so it would be nice if this tool would be able to have that too (and I really like your work although I mainly use it for the IV :P ).

**Comment by mackhankins** [comment]
@SteinerKD I think it would be great.  I've never seen them in the decimal format, but I honestly haven't used any other tools other than this one.  I always assumed it came from the servers that way.  I'm going to close this for now since we're trying to get v1.1.1 out the door.  Open another issue if you make progress with pogobuff.
